name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: EmaadAkhter
          outputs: |
            dist/github-contribution-grid-snake.svg
          # Add these for a darker grid:
          color_snake: "#FF61D7"
          color_grid: "dark" # or use a hex code, e.g., "#22232e"

      - name: Push SVG to the output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
